"use client"

import type { RiskFinding } from "@/lib/types"
import { Download, FileText } from "lucide-react"
import { Button } from "@/components/ui/button"

interface ExportReportProps {
  findings: RiskFinding[]
  lastUpdated?: Date
}

export function ExportReport({ findings, lastUpdated }: ExportReportProps) {
  const generateTextReport = () => {
    let report = "OAUTHSENTRY SECURITY FINDINGS REPORT\n"
    report += "=====================================\n\n"
    report += `Generated: ${new Date().toLocaleString()}\n`
    report += `Total Findings: ${findings.length}\n`
    report += `Critical: ${findings.filter((f) => f.level === "critical").length}\n`
    report += `High: ${findings.filter((f) => f.level === "high").length}\n`
    report += `Medium: ${findings.filter((f) => f.level === "medium").length}\n`
    report += `Low: ${findings.filter((f) => f.level === "low").length}\n\n`

    report += "EXECUTIVE SUMMARY\n"
    report += "==================\n"
    const criticalFindings = findings.filter((f) => f.level === "critical")
    if (criticalFindings.length > 0) {
      report += `WARNING: ${criticalFindings.length} critical findings require immediate attention.\n\n`
    }

    report += "TOP FINDINGS\n"
    report += "============\n"
    findings
      .sort((a, b) => b.score - a.score)
      .slice(0, 5)
      .forEach((f, i) => {
        report += `\n${i + 1}. [${f.level.toUpperCase()}] ${f.headline} (Score: ${f.score}/100)\n`
        report += `   Asset: ${f.asset.name} (${f.asset.identifier})\n`
        report += `   Reasoning: ${f.reasoning}\n`
        report += `   Recommendation: ${f.recommendation}\n`
      })

    report += "\n\nDETAILED FINDINGS\n"
    report += "==================\n"
    findings.forEach((f, i) => {
      report += `\n[${i + 1}] ${f.headline}\n`
      report += `Level: ${f.level.toUpperCase()}\n`
      report += `Score: ${f.score}/100\n`
      report += `Asset: ${f.asset.name} (${f.asset.kind})\n`
      report += `Identifier: ${f.asset.identifier}\n`
      report += `\nReasoning:\n${f.reasoning}\n`
      report += `\nRisk Factors:\n`
      f.factors.forEach((factor) => {
        report += `- ${factor.label}: ${factor.detail}\n`
      })
      report += `\nRecommendation:\n${f.recommendation}\n`
      if (f.cveReferences && f.cveReferences.length > 0) {
        report += `\nThreat Intelligence:\n`
        f.cveReferences.forEach((ref) => {
          report += `- ${ref.id} (CVSS ${ref.score}) - ${ref.source}\n`
        })
      }
    })

    report += "\n\nREMEDIATION SUMMARY\n"
    report += "===================\n"
    report += `Total Resolved: ${findings.filter((f) => f.remediationStatus === "resolved").length}\n`
    report += `In Progress: ${findings.filter((f) => f.remediationStatus === "in-progress").length}\n`
    report += `Open: ${findings.filter((f) => !f.remediationStatus || f.remediationStatus === "open").length}\n`

    report += "\n\nReport generated by OAuthSentry\n"
    report += `Timestamp: ${new Date().toISOString()}\n`

    return report
  }

  const handleExportText = () => {
    const report = generateTextReport()
    const element = document.createElement("a")
    element.setAttribute(
      "href",
      "data:text/plain;charset=utf-8," + encodeURIComponent(report)
    )
    element.setAttribute("download", `oauthsentry-report-${Date.now()}.txt`)
    element.style.display = "none"
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  const handleExportJSON = () => {
    const report = {
      generated: new Date().toISOString(),
      summary: {
        totalFindings: findings.length,
        critical: findings.filter((f) => f.level === "critical").length,
        high: findings.filter((f) => f.level === "high").length,
        medium: findings.filter((f) => f.level === "medium").length,
        low: findings.filter((f) => f.level === "low").length,
      },
      findings: findings.map((f) => ({
        asset: f.asset.name,
        level: f.level,
        score: f.score,
        headline: f.headline,
        reasoning: f.reasoning,
        recommendation: f.recommendation,
        remediationStatus: f.remediationStatus,
        cveReferences: f.cveReferences,
      })),
    }

    const element = document.createElement("a")
    element.setAttribute(
      "href",
      "data:text/plain;charset=utf-8," + encodeURIComponent(JSON.stringify(report, null, 2))
    )
    element.setAttribute("download", `oauthsentry-report-${Date.now()}.json`)
    element.style.display = "none"
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  return (
    <div className="flex gap-2">
      <Button
        onClick={handleExportText}
        variant="outline"
        size="sm"
        className="gap-1.5 text-xs"
      >
        <Download className="h-3.5 w-3.5" />
        Export Report (TXT)
      </Button>
      <Button
        onClick={handleExportJSON}
        variant="outline"
        size="sm"
        className="gap-1.5 text-xs"
      >
        <FileText className="h-3.5 w-3.5" />
        Export Report (JSON)
      </Button>
    </div>
  )
}
