"use client"

import type { RiskFinding } from "@/lib/types"
import { Download, FileText, File } from "lucide-react"
import { Button } from "@/components/ui/button"

interface ExportReportProps {
  findings: RiskFinding[]
  lastUpdated?: Date
}

export function ExportReport({ findings, lastUpdated }: ExportReportProps) {
  const handleExportPDF = async () => {
    try {
      const { jsPDF } = await import("jspdf")
      const doc = new jsPDF()

      // Title
      doc.setFontSize(16)
      doc.text("OAuthSentry Security Report", 20, 20)

      // Summary
      doc.setFontSize(10)
      doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 30)
      doc.text(`Total Findings: ${findings.length}`, 20, 37)

      const criticalCount = findings.filter((f) => f.level === "critical").length
      const highCount = findings.filter((f) => f.level === "high").length
      doc.text(`Critical: ${criticalCount} | High: ${highCount}`, 20, 44)

      let yPosition = 55
      const pageHeight = doc.internal.pageSize.height
      const maxY = pageHeight - 20

      // Add findings
      findings.slice(0, 10).forEach((f, i) => {
        if (yPosition > maxY) {
          doc.addPage()
          yPosition = 20
        }

        doc.setFontSize(11)
        doc.setTextColor(
          f.level === "critical" ? 220 : f.level === "high" ? 249 : 51,
          f.level === "critical" ? 38 : f.level === "high" ? 115 : 65,
          f.level === "critical" ? 38 : f.level === "high" ? 22 : 85
        )
        doc.text(`${i + 1}. ${f.headline}`, 20, yPosition)

        doc.setFontSize(9)
        doc.setTextColor(80, 80, 80)
        yPosition += 7
        doc.text(`Score: ${f.score}/100 | Level: ${f.level.toUpperCase()}`, 20, yPosition)
        yPosition += 5
        doc.text(`Asset: ${f.asset.name}`, 20, yPosition)
        yPosition += 8
      })

      doc.save(`oauthsentry-report-${Date.now()}.pdf`)
    } catch (error) {
      console.error("PDF export failed:", error)
      alert("PDF export failed. Please use JSON or TXT export instead.")
    }
  }

  const handleExportText = () => {
    let report = "OAUTHSENTRY SECURITY FINDINGS REPORT\n"
    report += "=====================================\n\n"
    report += `Generated: ${new Date().toLocaleString()}\n`
    report += `Total Findings: ${findings.length}\n`
    report += `Critical: ${findings.filter((f) => f.level === "critical").length}\n`
    report += `High: ${findings.filter((f) => f.level === "high").length}\n`
    report += `Medium: ${findings.filter((f) => f.level === "medium").length}\n`
    report += `Low: ${findings.filter((f) => f.level === "low").length}\n\n`

    report += "EXECUTIVE SUMMARY\n"
    report += "==================\n"
    const criticalFindings = findings.filter((f) => f.level === "critical")
    if (criticalFindings.length > 0) {
      report += `WARNING: ${criticalFindings.length} critical findings require immediate attention.\n\n`
    }

    report += "TOP FINDINGS\n"
    report += "============\n"
    findings
      .sort((a, b) => b.score - a.score)
      .slice(0, 5)
      .forEach((f, i) => {
        report += `\n${i + 1}. [${f.level.toUpperCase()}] ${f.headline} (Score: ${f.score}/100)\n`
        report += `   Asset: ${f.asset.name} (${f.asset.identifier})\n`
        report += `   Reasoning: ${f.reasoning}\n`
        report += `   Recommendation: ${f.recommendation}\n`
      })

    report += "\n\nREMEDIATION SUMMARY\n"
    report += "===================\n"
    report += `Total Resolved: ${findings.filter((f) => f.remediationStatus === "resolved").length}\n`
    report += `In Progress: ${findings.filter((f) => f.remediationStatus === "in-progress").length}\n`
    report += `Open: ${findings.filter((f) => !f.remediationStatus || f.remediationStatus === "open").length}\n`

    report += "\n\nReport generated by OAuthSentry\n"
    report += `Timestamp: ${new Date().toISOString()}\n`

    const element = document.createElement("a")
    element.setAttribute(
      "href",
      "data:text/plain;charset=utf-8," + encodeURIComponent(report)
    )
    element.setAttribute("download", `oauthsentry-report-${Date.now()}.txt`)
    element.style.display = "none"
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  const handleExportJSON = () => {
    const report = {
      generated: new Date().toISOString(),
      summary: {
        totalFindings: findings.length,
        critical: findings.filter((f) => f.level === "critical").length,
        high: findings.filter((f) => f.level === "high").length,
        medium: findings.filter((f) => f.level === "medium").length,
        low: findings.filter((f) => f.level === "low").length,
      },
      findings: findings.map((f) => ({
        asset: f.asset.name,
        level: f.level,
        score: f.score,
        headline: f.headline,
        reasoning: f.reasoning,
        recommendation: f.recommendation,
        remediationStatus: f.remediationStatus,
        cveReferences: f.cveReferences,
      })),
    }

    const element = document.createElement("a")
    element.setAttribute(
      "href",
      "data:text/plain;charset=utf-8," + encodeURIComponent(JSON.stringify(report, null, 2))
    )
    element.setAttribute("download", `oauthsentry-report-${Date.now()}.json`)
    element.style.display = "none"
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  return (
    <div className="flex gap-2 flex-wrap">
      <Button
        onClick={handleExportPDF}
        variant="outline"
        size="sm"
        className="gap-1.5 text-xs"
        title="Export as PDF (requires jsPDF)"
      >
        <File className="h-3.5 w-3.5" />
        Export as PDF
      </Button>
      <Button
        onClick={handleExportText}
        variant="outline"
        size="sm"
        className="gap-1.5 text-xs"
      >
        <Download className="h-3.5 w-3.5" />
        Export as TXT
      </Button>
      <Button
        onClick={handleExportJSON}
        variant="outline"
        size="sm"
        className="gap-1.5 text-xs"
      >
        <FileText className="h-3.5 w-3.5" />
        Export as JSON
      </Button>
    </div>
  )
}
