"use client"

import type { RiskFinding } from "@/lib/types"

// Pre-loaded demo findings showing real security risks for instant testing
export const demoFindings: RiskFinding[] = [
  {
    assetId: "context-ai-oauth",
    asset: {
      id: "context-ai-oauth",
      kind: "oauth_app",
      name: "Context.ai",
      identifier: "110671459871-30f1spbu0hptbs60cb4vsmv791tbbvqj.apps.googleusercontent.com",
      owner: "Context AI Inc",
      scopes: ["drive.file", "calendar.readonly", "gmail.readonly", "admin.directory.user.readonly"],
    },
    score: 95,
    level: "critical",
    headline: "OAuth app involved in major security breach with admin scope",
    reasoning: "The Context.ai OAuth app was compromised in April 2026, allowing attackers to pivot into Google Workspace. The app has admin directory scopes, enabling unauthorized user enumeration and credential theft. Multiple downstream consumers are affected.",
    factors: [
      { label: "Breach History", detail: "Confirmed security incident in April 2026 with active attacker exploitation" },
      { label: "Access Vector", detail: "OAuth admin scopes enable access to organizational directory and identities" },
      { label: "Affected Consumers", detail: "450+ organizations, 10K+ users potentially exposed" },
      { label: "Time to Exploit", detail: "Attacker already accessed internal systems within 2 weeks of breach" },
    ],
    iocMatches: ["context-ai-breach-2026"],
    recommendation: "IMMEDIATE: 1. Revoke all Context.ai OAuth permissions. 2. Rotate all GCP service account keys. 3. Review Google Workspace audit logs for unauthorized access. 4. Notify all users to change passwords.",
    ticketStatus: "filed",
    alertStatus: "sent",
    remediationStatus: "in-progress",
    remediationDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    linkedTicketUrl: "https://linear.app/oauthsentry/issue/OAU-5",
    cveReferences: [
      { id: "CVE-2026-0047", score: 9.8, source: "NVD" },
      { id: "GHSA-2026-1234", score: 10.0, source: "GitHub Advisory" },
    ],
  },
  {
    assetId: "stalebot-pro",
    asset: {
      id: "stalebot-pro",
      kind: "oauth_app",
      name: "stalebot-pro",
      identifier: "stalebot-pro.com",
      owner: "stalebot-pro (abandoned)",
      scopes: ["repo", "delete_repo"],
    },
    score: 85,
    level: "critical",
    headline: "High-Risk OAuth App: Vendor sunset with critical permissions",
    reasoning: "The stalebot-pro OAuth app has been abandoned for 11 months and the original maintainer is no longer supporting it. Version 3.2.0 introduced critical permission escalation (delete_repo) without changelog disclosure. New ownership transferred to unknown entity raises supply-chain risk.",
    factors: [
      { label: "Vendor Sunset", detail: "Original maintainer departed 11 months ago, indicating lack of ongoing support" },
      { label: "Permission Escalation", detail: "New version v3.2.0 added delete_repo scope without disclosure" },
      { label: "Ownership Transfer", detail: "Repository transferred to new owner with unknown reputation" },
      { label: "IOC Match", detail: "Identified as typosquat candidate in security advisory" },
    ],
    iocMatches: ["stalebot-pro-abandoned", "ownership-change-detected"],
    recommendation: "HIGH: 1. Disable or remove stalebot-pro from GitHub immediately. 2. Audit repository deletion logs for anomalies. 3. Evaluate alternative maintained stale-issue management solutions. 4. Review all GitHub actions run by this app.",
    ticketStatus: "filed",
    alertStatus: "sent",
    remediationStatus: "open",
    linkedTicketUrl: "https://linear.app/oauthsentry/issue/OAU-6",
    cveReferences: [
      { id: "GHSA-2026-5678", score: 8.2, source: "GitHub Advisory" },
    ],
  },
  {
    assetId: "clipboardz-npm",
    asset: {
      id: "clipboardz-npm",
      kind: "npm_package",
      name: "clipboardz",
      identifier: "clipboardz@1.0.0",
      owner: "npm.js",
    },
    score: 85,
    level: "critical",
    headline: "Critical: Malicious npm package found in dependencies",
    reasoning: "The npm package 'clipboardz' is a confirmed typosquat of 'clipboard', containing malicious code that exfiltrates environment variables during installation. The malicious code sends all ENV vars to dns-cache.io. 14 known downstream consumers affected, including major SaaS providers.",
    factors: [
      { label: "Typosquatting Risk", detail: "Package name 'clipboardz' closely resembles 'clipboard' to mislead users" },
      { label: "Malicious Behavior", detail: "Post-installation hook exfiltrates all environment variables to attacker server" },
      { label: "Affected Consumers", detail: "14 downstream npm packages and major applications depend on this" },
      { label: "High Severity Advisory", detail: "Published security advisory classifies as critical (CVSS 10.0)" },
    ],
    iocMatches: ["clipboardz-typosquat", "malicious-npm-package"],
    recommendation: "CRITICAL: 1. Remove clipboardz from all package.json files immediately. 2. Purge node_modules and reinstall dependencies. 3. Rotate all environment variables and secrets used in build process. 4. Audit GitHub Actions logs for exposed secrets.",
    ticketStatus: "filed",
    alertStatus: "sent",
    remediationStatus: "open",
    linkedTicketUrl: "https://linear.app/oauthsentry/issue/OAU-7",
    cveReferences: [
      { id: "CVE-2026-0512", score: 10.0, source: "NVD" },
      { id: "CISA-KEV", score: 10.0, source: "CISA Known Exploited Vulnerabilities" },
    ],
  },
  {
    assetId: "meetscribe-ai",
    asset: {
      id: "meetscribe-ai",
      kind: "saas_tool",
      name: "MeetScribe AI",
      identifier: "meetscribe.ai",
      owner: "MeetScribe Inc",
      scopes: ["calendar.read", "drive.write", "gmail.read"],
    },
    score: 85,
    level: "critical",
    headline: "Excessive OAuth scope drift in AI meeting tool",
    reasoning: "MeetScribe AI requests excessive scopes including drive.write (can modify files) and gmail.read despite only needing to record meetings. The app was not updated since 2024 and known vulnerabilities exist in its dependency chain. Multiple security advisories exist.",
    factors: [
      { label: "Scope Drift", detail: "App requests drive.write and gmail.read despite only needing meeting recording" },
      { label: "No Recent Updates", detail: "Last update was April 2024, 24 months without security patches" },
      { label: "Dependency Vulnerabilities", detail: "App uses outdated libraries with 3 known CVEs" },
      { label: "Excessive Access", detail: "Can read employee emails and modify shared documents" },
    ],
    iocMatches: ["meetscribe-scope-drift", "outdated-dependencies"],
    recommendation: "HIGH: 1. Request MeetScribe to reduce OAuth scopes to meeting-recording only. 2. Audit files modified by MeetScribe in shared drives. 3. Review email access logs. 4. Consider switching to privacy-focused alternative if scopes not reduced.",
    ticketStatus: "none",
    alertStatus: "sent",
    remediationStatus: "open",
    cveReferences: [
      { id: "CVE-2024-1234", score: 7.5, source: "NVD" },
      { id: "CVE-2024-5678", score: 6.8, source: "NVD" },
    ],
  },
  {
    assetId: "evalrunner-npm",
    asset: {
      id: "evalrunner-npm",
      kind: "npm_package",
      name: "evalrunner",
      identifier: "evalrunner@2.1.5",
      owner: "npm.js",
    },
    score: 75,
    level: "high",
    headline: "npm package with outdated vulnerable transitive dependency",
    reasoning: "The evalrunner npm package depends on outdated lodash version (4.17.19) with known RCE vulnerability. The maintainer is unresponsive to security patches. Waiting for new release has exposed all downstream consumers to CVE-2021-23337.",
    factors: [
      { label: "Transitive Dependency Risk", detail: "Depends on lodash 4.17.19 with known RCE vulnerability" },
      { label: "Maintainer Unresponsive", detail: "No response to security issue reports for 6+ months" },
      { label: "Public Exploit Available", detail: "Exploit code for CVE-2021-23337 publicly available on GitHub" },
      { label: "Wide Adoption", detail: "Package has 50K+ weekly downloads exposing many projects" },
    ],
    iocMatches: ["evalrunner-outdated-lodash"],
    recommendation: "HIGH: 1. Upgrade to evalrunner@3.0.0+ which uses lodash@4.17.21. 2. If upgrade not possible, audit code for dangerous lodash usage patterns. 3. Monitor for any suspicious code execution in production.",
    ticketStatus: "none",
    alertStatus: "none",
    remediationStatus: "open",
    cveReferences: [
      { id: "CVE-2021-23337", score: 9.1, source: "NVD" },
    ],
  },
]
